/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var SidebarOrganizer = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined")
      return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
  });
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/main.ts
  var main_exports = {};
  __export(main_exports, {
    SidebarOrganizerPlugin: () => SidebarOrganizerPlugin,
    default: () => main_default
  });
  var import_obsidian3 = __require("obsidian");

  // src/types.ts
  var DEFAULT_SETTINGS = {
    enabled: true,
    blurEffect: true,
    blurIntensity: 16,
    customGroups: [],
    language: "auto"
  };

  // src/i18n.ts
  var translations = {
    zh: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "\u5C06\u540C\u4E00\u63D2\u4EF6\u7684\u591A\u4E2A\u4FA7\u8FB9\u680F\u56FE\u6807\u5408\u5E76\u4E3A\u4E00\u4E2A\uFF0C\u60AC\u505C\u663E\u793A\u529F\u80FD\u83DC\u5355",
      enableOrganizer: "\u542F\u7528\u4FA7\u8FB9\u680F\u6574\u7406",
      enableOrganizerDesc: "\u5F00\u542F/\u5173\u95ED\u4FA7\u8FB9\u680F\u56FE\u6807\u5408\u5E76\u529F\u80FD",
      blurEffect: "\u6BDB\u73BB\u7483\u6548\u679C",
      blurEffectDesc: "\u4E3A\u5F39\u51FA\u83DC\u5355\u6DFB\u52A0\u6A21\u7CCA\u80CC\u666F\u6548\u679C",
      blurIntensity: "\u6A21\u7CCA\u5F3A\u5EA6",
      blurIntensityDesc: "\u8C03\u6574\u80CC\u666F\u6A21\u7CCA\u7A0B\u5EA6 (\u5F53\u524D: {value}px)",
      refreshSidebar: "\u5237\u65B0\u4FA7\u8FB9\u680F",
      refreshSidebarDesc: "\u91CD\u65B0\u68C0\u6D4B\u5E76\u6574\u7406\u4FA7\u8FB9\u680F\u56FE\u6807",
      refreshBtn: "\u5237\u65B0",
      refreshNotice: "\u4FA7\u8FB9\u680F\u5DF2\u5237\u65B0",
      customGroups: "\u81EA\u5B9A\u4E49\u5206\u7EC4",
      customGroupsDesc: "\u521B\u5EFA\u81EA\u5B9A\u4E49\u5206\u7EC4\uFF0C\u624B\u52A8\u9009\u62E9\u8981\u5408\u5E76\u7684\u529F\u80FD",
      createGroup: "\u521B\u5EFA\u5206\u7EC4",
      editGroup: "\u7F16\u8F91",
      deleteGroup: "\u5220\u9664",
      groupDeleted: "\u5206\u7EC4\u5DF2\u5220\u9664",
      actionCount: "{count} \u4E2A\u529F\u80FD",
      default: "\u9ED8\u8BA4",
      autoGroups: "\u81EA\u52A8\u68C0\u6D4B\u5206\u7EC4",
      autoGroupsDesc: "\u4EE5\u4E0B\u63D2\u4EF6\u6709\u591A\u4E2A\u4FA7\u8FB9\u680F\u529F\u80FD\uFF0C\u5DF2\u81EA\u52A8\u5408\u5E76\u3002\u70B9\u51FB\u7F16\u8F91\u53EF\u81EA\u5B9A\u4E49\u540D\u79F0\u548C\u56FE\u6807\u3002",
      autoGroupBadge: "\u81EA\u52A8",
      createGroupTitle: "\u521B\u5EFA\u5206\u7EC4",
      editGroupTitle: "\u7F16\u8F91\u5206\u7EC4",
      selectFunctions: "\u9009\u62E9\u529F\u80FD",
      selectFunctionsDesc: "\u70B9\u51FB\u529F\u80FD\u6DFB\u52A0\u5230\u53F3\u4FA7\u5206\u7EC4\uFF0C\u70B9\u51FB\u5206\u7EC4\u6807\u9898\u53EF\u5168\u9009\u8BE5\u7EC4",
      availableFunctions: "\u53EF\u7528\u529F\u80FD",
      groupFunctions: "\u5206\u7EC4\u529F\u80FD",
      clickToAdd: "\u70B9\u51FB\u5DE6\u4FA7\u529F\u80FD\u6DFB\u52A0\u5230\u5206\u7EC4",
      nextStep: "\u4E0B\u4E00\u6B65",
      previousStep: "\u4E0A\u4E00\u6B65",
      setNameAndIcon: "\u8BBE\u7F6E\u540D\u79F0\u548C\u56FE\u6807",
      groupName: "\u5206\u7EC4\u540D\u79F0",
      groupNameDesc: "\u4E3A\u5206\u7EC4\u6307\u5B9A\u4E00\u4E2A\u540D\u79F0",
      groupNamePlaceholder: "\u5982: \u5E38\u7528\u5DE5\u5177",
      customIcon: "\u81EA\u5B9A\u4E49\u56FE\u6807\uFF08\u53EF\u9009\uFF09",
      clickSelectAll: "\u70B9\u51FB\u5168\u9009",
      selectAll: "\u5168\u9009",
      pleaseEnterName: "\u8BF7\u8F93\u5165\u5206\u7EC4\u540D\u79F0",
      pleaseSelectOne: "\u8BF7\u81F3\u5C11\u9009\u62E9\u4E00\u4E2A\u529F\u80FD",
      groupCreated: "\u5206\u7EC4\u5DF2\u521B\u5EFA",
      groupUpdated: "\u5206\u7EC4\u5DF2\u66F4\u65B0",
      usageInstructions: "\u4F7F\u7528\u8BF4\u660E",
      instruction1: '\u70B9\u51FB"\u521B\u5EFA\u5206\u7EC4"\u53EF\u4EE5\u5C06\u591A\u4E2A\u4FA7\u8FB9\u680F\u56FE\u6807\u5408\u5E76\u4E3A\u4E00\u4E2A',
      instruction2: "\u60AC\u505C\u5728\u5408\u5E76\u540E\u7684\u56FE\u6807\u4E0A\u4F1A\u663E\u793A\u529F\u80FD\u83DC\u5355",
      instruction3: "\u70B9\u51FB\u529F\u80FD\u9879\u5373\u53EF\u6FC0\u6D3B\u5BF9\u5E94\u529F\u80FD",
      instruction4: "\u70B9\u51FB\u5408\u5E76\u56FE\u6807\u53EF\u4EE5\u76F4\u63A5\u6253\u5F00\u7B2C\u4E00\u4E2A\u529F\u80FD",
      language: "\u8BED\u8A00",
      languageDesc: "\u9009\u62E9\u63D2\u4EF6\u754C\u9762\u8BED\u8A00\uFF08\u9ED8\u8BA4\u8DDF\u968F Obsidian \u8BBE\u7F6E\uFF09",
      auto: "\u81EA\u52A8",
      assigned: "\u5DF2\u5206\u914D",
      cancel: "\u53D6\u6D88",
      save: "\u4FDD\u5B58",
      noPreview: "\u6682\u65E0\u9884\u89C8",
      svgPlaceholder: "\u8F93\u5165 SVG \u4EE3\u7801\uFF08\u53EF\u9009\uFF09",
      examples: "\u793A\u4F8B\uFF1A",
      folder: "\u6587\u4EF6\u5939",
      star: "\u661F\u6807",
      grid: "\u7F51\u683C"
    },
    en: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "Merge multiple sidebar icons from the same plugin into one, hover to show function menu",
      enableOrganizer: "Enable Sidebar Organizer",
      enableOrganizerDesc: "Turn on/off sidebar icon merging function",
      blurEffect: "Blur Effect",
      blurEffectDesc: "Add blur background effect to popup menu",
      blurIntensity: "Blur Intensity",
      blurIntensityDesc: "Adjust background blur level (current: {value}px)",
      refreshSidebar: "Refresh Sidebar",
      refreshSidebarDesc: "Re-detect and organize sidebar icons",
      refreshBtn: "Refresh",
      refreshNotice: "Sidebar refreshed",
      customGroups: "Custom Groups",
      customGroupsDesc: "Create custom groups, manually select functions to merge",
      createGroup: "Create Group",
      editGroup: "Edit",
      deleteGroup: "Delete",
      groupDeleted: "Group deleted",
      actionCount: "{count} functions",
      default: "Default",
      autoGroups: "Auto-detected Groups",
      autoGroupsDesc: "Plugins with multiple sidebar actions are grouped automatically. Click edit to customize name and icon.",
      autoGroupBadge: "Auto",
      createGroupTitle: "Create Group",
      editGroupTitle: "Edit Group",
      selectFunctions: "Select Functions",
      selectFunctionsDesc: "Click functions to add to group, click group title to select all",
      availableFunctions: "Available Functions",
      groupFunctions: "Group Functions",
      clickToAdd: "Click left functions to add to group",
      nextStep: "Next",
      previousStep: "Previous",
      setNameAndIcon: "Set Name and Icon",
      groupName: "Group Name",
      groupNameDesc: "Specify a name for the group",
      groupNamePlaceholder: "e.g.: Common Tools",
      customIcon: "Custom Icon (Optional)",
      clickSelectAll: "Click to select all",
      selectAll: "Select All",
      pleaseEnterName: "Please enter group name",
      pleaseSelectOne: "Please select at least one function",
      groupCreated: "Group created",
      groupUpdated: "Group updated",
      usageInstructions: "Usage Instructions",
      instruction1: 'Click "Create Group" to merge multiple sidebar icons into one',
      instruction2: "Hover over merged icon to show function menu",
      instruction3: "Click function item to activate corresponding function",
      instruction4: "Click merged icon to directly open the first function",
      language: "Language",
      languageDesc: "Select plugin interface language (default follows Obsidian settings)",
      auto: "Auto",
      assigned: "Assigned",
      cancel: "Cancel",
      save: "Save",
      noPreview: "No preview",
      svgPlaceholder: "Enter SVG code (optional)",
      examples: "Examples:",
      folder: "Folder",
      star: "Star",
      grid: "Grid"
    },
    ja: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "\u540C\u3058\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u8907\u6570\u306E\u30B5\u30A4\u30C9\u30D0\u30FC\u30A2\u30A4\u30B3\u30F3\u30921\u3064\u306B\u307E\u3068\u3081\u3001\u30DB\u30D0\u30FC\u3067\u6A5F\u80FD\u30E1\u30CB\u30E5\u30FC\u3092\u8868\u793A",
      enableOrganizer: "\u30B5\u30A4\u30C9\u30D0\u30FC\u6574\u7406\u3092\u6709\u52B9\u5316",
      enableOrganizerDesc: "\u30B5\u30A4\u30C9\u30D0\u30FC\u30A2\u30A4\u30B3\u30F3\u306E\u7D71\u5408\u6A5F\u80FD\u3092\u30AA\u30F3/\u30AA\u30D5",
      blurEffect: "\u30D6\u30E9\u30FC\u52B9\u679C",
      blurEffectDesc: "\u30DD\u30C3\u30D7\u30A2\u30C3\u30D7\u30E1\u30CB\u30E5\u30FC\u306B\u80CC\u666F\u30D6\u30E9\u30FC\u52B9\u679C\u3092\u8FFD\u52A0",
      blurIntensity: "\u30D6\u30E9\u30FC\u5F37\u5EA6",
      blurIntensityDesc: "\u80CC\u666F\u306E\u30D6\u30E9\u30FC\u30EC\u30D9\u30EB\u3092\u8ABF\u6574\uFF08\u73FE\u5728: {value}px\uFF09",
      refreshSidebar: "\u30B5\u30A4\u30C9\u30D0\u30FC\u3092\u66F4\u65B0",
      refreshSidebarDesc: "\u30B5\u30A4\u30C9\u30D0\u30FC\u30A2\u30A4\u30B3\u30F3\u3092\u518D\u691C\u51FA\u3057\u3066\u6574\u7406",
      refreshBtn: "\u66F4\u65B0",
      refreshNotice: "\u30B5\u30A4\u30C9\u30D0\u30FC\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F",
      customGroups: "\u30AB\u30B9\u30BF\u30E0\u30B0\u30EB\u30FC\u30D7",
      customGroupsDesc: "\u30AB\u30B9\u30BF\u30E0\u30B0\u30EB\u30FC\u30D7\u3092\u4F5C\u6210\u3057\u3001\u7D71\u5408\u3059\u308B\u6A5F\u80FD\u3092\u624B\u52D5\u3067\u9078\u629E",
      createGroup: "\u30B0\u30EB\u30FC\u30D7\u4F5C\u6210",
      editGroup: "\u7DE8\u96C6",
      deleteGroup: "\u524A\u9664",
      groupDeleted: "\u30B0\u30EB\u30FC\u30D7\u3092\u524A\u9664\u3057\u307E\u3057\u305F",
      actionCount: "{count}\u500B\u306E\u6A5F\u80FD",
      default: "\u30C7\u30D5\u30A9\u30EB\u30C8",
      autoGroups: "\u81EA\u52D5\u691C\u51FA\u30B0\u30EB\u30FC\u30D7",
      autoGroupsDesc: "\u4EE5\u4E0B\u306E\u30D7\u30E9\u30B0\u30A4\u30F3\u306B\u306F\u8907\u6570\u306E\u30B5\u30A4\u30C9\u30D0\u30FC\u6A5F\u80FD\u304C\u3042\u308A\u3001\u81EA\u52D5\u7684\u306B\u30B0\u30EB\u30FC\u30D7\u5316\u3055\u308C\u3066\u3044\u307E\u3059\u3002\u7DE8\u96C6\u3057\u3066\u30AB\u30B9\u30BF\u30DE\u30A4\u30BA\u3067\u304D\u307E\u3059\u3002",
      autoGroupBadge: "\u81EA\u52D5",
      createGroupTitle: "\u30B0\u30EB\u30FC\u30D7\u4F5C\u6210",
      editGroupTitle: "\u30B0\u30EB\u30FC\u30D7\u7DE8\u96C6",
      selectFunctions: "\u6A5F\u80FD\u3092\u9078\u629E",
      selectFunctionsDesc: "\u6A5F\u80FD\u3092\u30AF\u30EA\u30C3\u30AF\u3057\u3066\u30B0\u30EB\u30FC\u30D7\u306B\u8FFD\u52A0\u3001\u30B0\u30EB\u30FC\u30D7\u30BF\u30A4\u30C8\u30EB\u3092\u30AF\u30EA\u30C3\u30AF\u3067\u5168\u9078\u629E",
      availableFunctions: "\u5229\u7528\u53EF\u80FD\u306A\u6A5F\u80FD",
      groupFunctions: "\u30B0\u30EB\u30FC\u30D7\u306E\u6A5F\u80FD",
      clickToAdd: "\u5DE6\u5074\u306E\u6A5F\u80FD\u3092\u30AF\u30EA\u30C3\u30AF\u3057\u3066\u30B0\u30EB\u30FC\u30D7\u306B\u8FFD\u52A0",
      nextStep: "\u6B21\u3078",
      previousStep: "\u623B\u308B",
      setNameAndIcon: "\u540D\u524D\u3068\u30A2\u30A4\u30B3\u30F3\u3092\u8A2D\u5B9A",
      groupName: "\u30B0\u30EB\u30FC\u30D7\u540D",
      groupNameDesc: "\u30B0\u30EB\u30FC\u30D7\u306E\u540D\u524D\u3092\u6307\u5B9A",
      groupNamePlaceholder: "\u4F8B: \u3088\u304F\u4F7F\u3046\u30C4\u30FC\u30EB",
      customIcon: "\u30AB\u30B9\u30BF\u30E0\u30A2\u30A4\u30B3\u30F3\uFF08\u4EFB\u610F\uFF09",
      clickSelectAll: "\u30AF\u30EA\u30C3\u30AF\u3067\u5168\u9078\u629E",
      selectAll: "\u5168\u9078\u629E",
      pleaseEnterName: "\u30B0\u30EB\u30FC\u30D7\u540D\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044",
      pleaseSelectOne: "\u5C11\u306A\u304F\u3068\u30821\u3064\u306E\u6A5F\u80FD\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044",
      groupCreated: "\u30B0\u30EB\u30FC\u30D7\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F",
      groupUpdated: "\u30B0\u30EB\u30FC\u30D7\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F",
      usageInstructions: "\u4F7F\u3044\u65B9",
      instruction1: "\u300C\u30B0\u30EB\u30FC\u30D7\u4F5C\u6210\u300D\u3092\u30AF\u30EA\u30C3\u30AF\u3057\u3066\u8907\u6570\u306E\u30B5\u30A4\u30C9\u30D0\u30FC\u30A2\u30A4\u30B3\u30F3\u30921\u3064\u306B\u307E\u3068\u3081\u308B",
      instruction2: "\u7D71\u5408\u3055\u308C\u305F\u30A2\u30A4\u30B3\u30F3\u306B\u30DB\u30D0\u30FC\u3059\u308B\u3068\u6A5F\u80FD\u30E1\u30CB\u30E5\u30FC\u304C\u8868\u793A\u3055\u308C\u307E\u3059",
      instruction3: "\u6A5F\u80FD\u9805\u76EE\u3092\u30AF\u30EA\u30C3\u30AF\u3059\u308B\u3068\u5BFE\u5FDC\u3059\u308B\u6A5F\u80FD\u304C\u8D77\u52D5\u3057\u307E\u3059",
      instruction4: "\u7D71\u5408\u30A2\u30A4\u30B3\u30F3\u3092\u30AF\u30EA\u30C3\u30AF\u3059\u308B\u3068\u6700\u521D\u306E\u6A5F\u80FD\u304C\u76F4\u63A5\u958B\u304D\u307E\u3059",
      language: "\u8A00\u8A9E",
      languageDesc: "\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u30A4\u30F3\u30BF\u30FC\u30D5\u30A7\u30FC\u30B9\u8A00\u8A9E\u3092\u9078\u629E\uFF08\u30C7\u30D5\u30A9\u30EB\u30C8\u306FObsidian\u306E\u8A2D\u5B9A\u306B\u5F93\u3046\uFF09",
      auto: "\u81EA\u52D5",
      assigned: "\u5272\u308A\u5F53\u3066\u6E08\u307F",
      cancel: "\u30AD\u30E3\u30F3\u30BB\u30EB",
      save: "\u4FDD\u5B58",
      noPreview: "\u30D7\u30EC\u30D3\u30E5\u30FC\u306A\u3057",
      svgPlaceholder: "SVG\u30B3\u30FC\u30C9\u3092\u5165\u529B\uFF08\u30AA\u30D7\u30B7\u30E7\u30F3\uFF09",
      examples: "\u4F8B\uFF1A",
      folder: "\u30D5\u30A9\u30EB\u30C0",
      star: "\u30B9\u30BF\u30FC",
      grid: "\u30B0\u30EA\u30C3\u30C9"
    },
    ko: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "\uB3D9\uC77C\uD55C \uD50C\uB7EC\uADF8\uC778\uC758 \uC5EC\uB7EC \uC0AC\uC774\uB4DC\uBC14 \uC544\uC774\uCF58\uC744 \uD558\uB098\uB85C \uD1B5\uD569\uD558\uACE0, \uB9C8\uC6B0\uC2A4 \uC624\uBC84\uB85C \uAE30\uB2A5 \uBA54\uB274 \uD45C\uC2DC",
      enableOrganizer: "\uC0AC\uC774\uB4DC\uBC14 \uC815\uB9AC \uD65C\uC131\uD654",
      enableOrganizerDesc: "\uC0AC\uC774\uB4DC\uBC14 \uC544\uC774\uCF58 \uD1B5\uD569 \uAE30\uB2A5 \uCF1C\uAE30/\uB044\uAE30",
      blurEffect: "\uBE14\uB7EC \uD6A8\uACFC",
      blurEffectDesc: "\uD31D\uC5C5 \uBA54\uB274\uC5D0 \uBC30\uACBD \uBE14\uB7EC \uD6A8\uACFC \uCD94\uAC00",
      blurIntensity: "\uBE14\uB7EC \uAC15\uB3C4",
      blurIntensityDesc: "\uBC30\uACBD \uBE14\uB7EC \uC218\uC900 \uC870\uC815 (\uD604\uC7AC: {value}px)",
      refreshSidebar: "\uC0AC\uC774\uB4DC\uBC14 \uC0C8\uB85C\uACE0\uCE68",
      refreshSidebarDesc: "\uC0AC\uC774\uB4DC\uBC14 \uC544\uC774\uCF58 \uC7AC\uAC10\uC9C0 \uBC0F \uC815\uB9AC",
      refreshBtn: "\uC0C8\uB85C\uACE0\uCE68",
      refreshNotice: "\uC0AC\uC774\uB4DC\uBC14\uAC00 \uC0C8\uB85C\uACE0\uCE68\uB418\uC5C8\uC2B5\uB2C8\uB2E4",
      customGroups: "\uC0AC\uC6A9\uC790 \uC815\uC758 \uADF8\uB8F9",
      customGroupsDesc: "\uC0AC\uC6A9\uC790 \uC815\uC758 \uADF8\uB8F9\uC744 \uC0DD\uC131\uD558\uACE0 \uD1B5\uD569\uD560 \uAE30\uB2A5\uC744 \uC9C1\uC811 \uC120\uD0DD",
      createGroup: "\uADF8\uB8F9 \uC0DD\uC131",
      editGroup: "\uD3B8\uC9D1",
      deleteGroup: "\uC0AD\uC81C",
      groupDeleted: "\uADF8\uB8F9\uC774 \uC0AD\uC81C\uB418\uC5C8\uC2B5\uB2C8\uB2E4",
      actionCount: "{count}\uAC1C \uAE30\uB2A5",
      default: "\uAE30\uBCF8\uAC12",
      autoGroups: "\uC790\uB3D9 \uAC10\uC9C0 \uADF8\uB8F9",
      autoGroupsDesc: "\uB2E4\uC74C \uD50C\uB7EC\uADF8\uC778\uC5D0\uB294 \uC5EC\uB7EC \uC0AC\uC774\uB4DC\uBC14 \uAE30\uB2A5\uC774 \uC788\uC73C\uBA70 \uC790\uB3D9\uC73C\uB85C \uADF8\uB8F9\uD654\uB429\uB2C8\uB2E4. \uD3B8\uC9D1\uD558\uC5EC \uC0AC\uC6A9\uC790 \uC815\uC758\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
      autoGroupBadge: "\uC790\uB3D9",
      createGroupTitle: "\uADF8\uB8F9 \uC0DD\uC131",
      editGroupTitle: "\uADF8\uB8F9 \uD3B8\uC9D1",
      selectFunctions: "\uAE30\uB2A5 \uC120\uD0DD",
      selectFunctionsDesc: "\uAE30\uB2A5\uC744 \uD074\uB9AD\uD558\uC5EC \uADF8\uB8F9\uC5D0 \uCD94\uAC00, \uADF8\uB8F9 \uC81C\uBAA9 \uD074\uB9AD\uC73C\uB85C \uC804\uCCB4 \uC120\uD0DD",
      availableFunctions: "\uC0AC\uC6A9 \uAC00\uB2A5\uD55C \uAE30\uB2A5",
      groupFunctions: "\uADF8\uB8F9 \uAE30\uB2A5",
      clickToAdd: "\uC67C\uCABD \uAE30\uB2A5\uC744 \uD074\uB9AD\uD558\uC5EC \uADF8\uB8F9\uC5D0 \uCD94\uAC00",
      nextStep: "\uB2E4\uC74C",
      previousStep: "\uC774\uC804",
      setNameAndIcon: "\uC774\uB984 \uBC0F \uC544\uC774\uCF58 \uC124\uC815",
      groupName: "\uADF8\uB8F9 \uC774\uB984",
      groupNameDesc: "\uADF8\uB8F9\uC758 \uC774\uB984\uC744 \uC9C0\uC815\uD558\uC138\uC694",
      groupNamePlaceholder: "\uC608: \uC790\uC8FC \uC0AC\uC6A9\uD558\uB294 \uB3C4\uAD6C",
      customIcon: "\uC0AC\uC6A9\uC790 \uC815\uC758 \uC544\uC774\uCF58 (\uC120\uD0DD\uC0AC\uD56D)",
      clickSelectAll: "\uD074\uB9AD\uD558\uC5EC \uC804\uCCB4 \uC120\uD0DD",
      selectAll: "\uC804\uCCB4 \uC120\uD0DD",
      pleaseEnterName: "\uADF8\uB8F9 \uC774\uB984\uC744 \uC785\uB825\uD558\uC138\uC694",
      pleaseSelectOne: "\uCD5C\uC18C \uD558\uB098\uC758 \uAE30\uB2A5\uC744 \uC120\uD0DD\uD558\uC138\uC694",
      groupCreated: "\uADF8\uB8F9\uC774 \uC0DD\uC131\uB418\uC5C8\uC2B5\uB2C8\uB2E4",
      groupUpdated: "\uADF8\uB8F9\uC774 \uC5C5\uB370\uC774\uD2B8\uB418\uC5C8\uC2B5\uB2C8\uB2E4",
      usageInstructions: "\uC0AC\uC6A9 \uBC29\uBC95",
      instruction1: '"\uADF8\uB8F9 \uC0DD\uC131"\uC744 \uD074\uB9AD\uD558\uC5EC \uC5EC\uB7EC \uC0AC\uC774\uB4DC\uBC14 \uC544\uC774\uCF58\uC744 \uD558\uB098\uB85C \uD1B5\uD569',
      instruction2: "\uD1B5\uD569\uB41C \uC544\uC774\uCF58\uC5D0 \uB9C8\uC6B0\uC2A4\uB97C \uC62C\uB9AC\uBA74 \uAE30\uB2A5 \uBA54\uB274\uAC00 \uD45C\uC2DC\uB429\uB2C8\uB2E4",
      instruction3: "\uAE30\uB2A5 \uD56D\uBAA9\uC744 \uD074\uB9AD\uD558\uBA74 \uD574\uB2F9 \uAE30\uB2A5\uC774 \uD65C\uC131\uD654\uB429\uB2C8\uB2E4",
      instruction4: "\uD1B5\uD569 \uC544\uC774\uCF58\uC744 \uD074\uB9AD\uD558\uBA74 \uCCAB \uBC88\uC9F8 \uAE30\uB2A5\uC774 \uBC14\uB85C \uC5F4\uB9BD\uB2C8\uB2E4",
      language: "\uC5B8\uC5B4",
      languageDesc: "\uD50C\uB7EC\uADF8\uC778 \uC778\uD130\uD398\uC774\uC2A4 \uC5B8\uC5B4 \uC120\uD0DD (\uAE30\uBCF8\uAC12\uC740 Obsidian \uC124\uC815 \uB530\uB984)",
      auto: "\uC790\uB3D9",
      assigned: "\uD560\uB2F9\uB428",
      cancel: "\uCDE8\uC18C",
      save: "\uC800\uC7A5",
      noPreview: "\uBBF8\uB9AC\uBCF4\uAE30 \uC5C6\uC74C",
      svgPlaceholder: "SVG \uCF54\uB4DC \uC785\uB825 (\uC120\uD0DD\uC0AC\uD56D)",
      examples: "\uC608\uC2DC:",
      folder: "\uD3F4\uB354",
      star: "\uBCC4",
      grid: "\uADF8\uB9AC\uB4DC"
    },
    de: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "Mehrere Sidebar-Symbole desselben Plugins zu einem zusammenfassen, Hover zeigt Funktionsmen\xFC",
      enableOrganizer: "Sidebar-Organisation aktivieren",
      enableOrganizerDesc: "Funktion zum Zusammenfassen von Sidebar-Symbolen ein-/ausschalten",
      blurEffect: "Unsch\xE4rfe-Effekt",
      blurEffectDesc: "Unsch\xE4rfe-Effekt f\xFCr Hintergrund des Popup-Men\xFCs hinzuf\xFCgen",
      blurIntensity: "Unsch\xE4rfe-Intensit\xE4t",
      blurIntensityDesc: "Hintergrundunsch\xE4rfe anpassen (aktuell: {value}px)",
      refreshSidebar: "Sidebar aktualisieren",
      refreshSidebarDesc: "Sidebar-Symbole erneut erkennen und organisieren",
      refreshBtn: "Aktualisieren",
      refreshNotice: "Sidebar wurde aktualisiert",
      customGroups: "Benutzerdefinierte Gruppen",
      customGroupsDesc: "Benutzerdefinierte Gruppen erstellen und Funktionen zum Zusammenfassen manuell ausw\xE4hlen",
      createGroup: "Gruppe erstellen",
      editGroup: "Bearbeiten",
      deleteGroup: "L\xF6schen",
      groupDeleted: "Gruppe gel\xF6scht",
      actionCount: "{count} Funktionen",
      default: "Standard",
      autoGroups: "Automatisch erkannte Gruppen",
      autoGroupsDesc: "Die folgenden Plugins haben mehrere Sidebar-Funktionen und werden automatisch gruppiert. Bearbeiten zum Anpassen.",
      autoGroupBadge: "Auto",
      createGroupTitle: "Gruppe erstellen",
      editGroupTitle: "Gruppe bearbeiten",
      selectFunctions: "Funktionen ausw\xE4hlen",
      selectFunctionsDesc: "Funktionen anklicken um zur Gruppe hinzuzuf\xFCgen, Gruppentitel anklicken f\xFCr Alle ausw\xE4hlen",
      availableFunctions: "Verf\xFCgbare Funktionen",
      groupFunctions: "Gruppenfunktionen",
      clickToAdd: "Linke Funktionen anklicken um zur Gruppe hinzuzuf\xFCgen",
      nextStep: "Weiter",
      previousStep: "Zur\xFCck",
      setNameAndIcon: "Name und Symbol festlegen",
      groupName: "Gruppenname",
      groupNameDesc: "Einen Namen f\xFCr die Gruppe angeben",
      groupNamePlaceholder: "z.B.: H\xE4ufig verwendete Tools",
      customIcon: "Benutzerdefiniertes Symbol (Optional)",
      clickSelectAll: "Klicken um alle auszuw\xE4hlen",
      selectAll: "Alle ausw\xE4hlen",
      pleaseEnterName: "Bitte Gruppennamen eingeben",
      pleaseSelectOne: "Bitte mindestens eine Funktion ausw\xE4hlen",
      groupCreated: "Gruppe erstellt",
      groupUpdated: "Gruppe aktualisiert",
      usageInstructions: "Bedienungsanleitung",
      instruction1: '"Gruppe erstellen" anklicken um mehrere Sidebar-Symbole zu einem zusammenzufassen',
      instruction2: "\xDCber zusammengefasstes Symbol hovern um Funktionsmen\xFC anzuzeigen",
      instruction3: "Funktion anklicken um entsprechende Funktion zu aktivieren",
      instruction4: "Zusammengefasstes Symbol anklicken um erste Funktion direkt zu \xF6ffnen",
      language: "Sprache",
      languageDesc: "Plugin-Oberfl\xE4chensprache ausw\xE4hlen (Standard folgt Obsidian-Einstellungen)",
      auto: "Automatisch",
      assigned: "Zugewiesen",
      cancel: "Abbrechen",
      save: "Speichern",
      noPreview: "Keine Vorschau",
      svgPlaceholder: "SVG-Code eingeben (optional)",
      examples: "Beispiele:",
      folder: "Ordner",
      star: "Stern",
      grid: "Raster"
    },
    ru: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "\u041E\u0431\u044A\u0435\u0434\u0438\u043D\u0438\u0442\u044C \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0437\u043D\u0430\u0447\u043A\u043E\u0432 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438 \u043E\u0434\u043D\u043E\u0433\u043E \u043F\u043B\u0430\u0433\u0438\u043D\u0430 \u0432 \u043E\u0434\u0438\u043D, \u043F\u0440\u0438 \u043D\u0430\u0432\u0435\u0434\u0435\u043D\u0438\u0438 \u043F\u043E\u043A\u0430\u0437\u0430\u0442\u044C \u043C\u0435\u043D\u044E \u0444\u0443\u043D\u043A\u0446\u0438\u0439",
      enableOrganizer: "\u0412\u043A\u043B\u044E\u0447\u0438\u0442\u044C \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044E \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438",
      enableOrganizerDesc: "\u0412\u043A\u043B\u044E\u0447\u0438\u0442\u044C/\u0432\u044B\u043A\u043B\u044E\u0447\u0438\u0442\u044C \u0444\u0443\u043D\u043A\u0446\u0438\u044E \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u0435\u043D\u0438\u044F \u0437\u043D\u0430\u0447\u043A\u043E\u0432 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438",
      blurEffect: "\u042D\u0444\u0444\u0435\u043A\u0442 \u0440\u0430\u0437\u043C\u044B\u0442\u0438\u044F",
      blurEffectDesc: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u044D\u0444\u0444\u0435\u043A\u0442 \u0440\u0430\u0437\u043C\u044B\u0442\u0438\u044F \u0444\u043E\u043D\u0430 \u0434\u043B\u044F \u0432\u0441\u043F\u043B\u044B\u0432\u0430\u044E\u0449\u0435\u0433\u043E \u043C\u0435\u043D\u044E",
      blurIntensity: "\u0418\u043D\u0442\u0435\u043D\u0441\u0438\u0432\u043D\u043E\u0441\u0442\u044C \u0440\u0430\u0437\u043C\u044B\u0442\u0438\u044F",
      blurIntensityDesc: "\u041D\u0430\u0441\u0442\u0440\u043E\u0438\u0442\u044C \u0443\u0440\u043E\u0432\u0435\u043D\u044C \u0440\u0430\u0437\u043C\u044B\u0442\u0438\u044F \u0444\u043E\u043D\u0430 (\u0442\u0435\u043A\u0443\u0449\u0435\u0435: {value}px)",
      refreshSidebar: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0431\u043E\u043A\u043E\u0432\u0443\u044E \u043F\u0430\u043D\u0435\u043B\u044C",
      refreshSidebarDesc: "\u041F\u043E\u0432\u0442\u043E\u0440\u043D\u043E \u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0438\u0442\u044C \u0438 \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u043E\u0432\u0430\u0442\u044C \u0437\u043D\u0430\u0447\u043A\u0438 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438",
      refreshBtn: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C",
      refreshNotice: "\u0411\u043E\u043A\u043E\u0432\u0430\u044F \u043F\u0430\u043D\u0435\u043B\u044C \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430",
      customGroups: "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0435 \u0433\u0440\u0443\u043F\u043F\u044B",
      customGroupsDesc: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0435 \u0433\u0440\u0443\u043F\u043F\u044B, \u0432\u0440\u0443\u0447\u043D\u0443\u044E \u0432\u044B\u0431\u0440\u0430\u0442\u044C \u0444\u0443\u043D\u043A\u0446\u0438\u0438 \u0434\u043B\u044F \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u0435\u043D\u0438\u044F",
      createGroup: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0433\u0440\u0443\u043F\u043F\u0443",
      editGroup: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C",
      deleteGroup: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C",
      groupDeleted: "\u0413\u0440\u0443\u043F\u043F\u0430 \u0443\u0434\u0430\u043B\u0435\u043D\u0430",
      actionCount: "{count} \u0444\u0443\u043D\u043A\u0446\u0438\u0439",
      default: "\u041F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
      autoGroups: "\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0435 \u0433\u0440\u0443\u043F\u043F\u044B",
      autoGroupsDesc: "\u0421\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u0435 \u043F\u043B\u0430\u0433\u0438\u043D\u044B \u0438\u043C\u0435\u044E\u0442 \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0444\u0443\u043D\u043A\u0446\u0438\u0439 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438 \u0438 \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0441\u0433\u0440\u0443\u043F\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u044B. \u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u0440\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0434\u043B\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438.",
      autoGroupBadge: "\u0410\u0432\u0442\u043E",
      createGroupTitle: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0433\u0440\u0443\u043F\u043F\u0443",
      editGroupTitle: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0433\u0440\u0443\u043F\u043F\u0443",
      selectFunctions: "\u0412\u044B\u0431\u0440\u0430\u0442\u044C \u0444\u0443\u043D\u043A\u0446\u0438\u0438",
      selectFunctionsDesc: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u043D\u0430 \u0444\u0443\u043D\u043A\u0446\u0438\u044E \u0447\u0442\u043E\u0431\u044B \u0434\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432 \u0433\u0440\u0443\u043F\u043F\u0443, \u043D\u0430\u0436\u043C\u0438\u0442\u0435 \u043D\u0430 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043E\u043A \u0433\u0440\u0443\u043F\u043F\u044B \u0447\u0442\u043E\u0431\u044B \u0432\u044B\u0431\u0440\u0430\u0442\u044C \u0432\u0441\u0435",
      availableFunctions: "\u0414\u043E\u0441\u0442\u0443\u043F\u043D\u044B\u0435 \u0444\u0443\u043D\u043A\u0446\u0438\u0438",
      groupFunctions: "\u0424\u0443\u043D\u043A\u0446\u0438\u0438 \u0433\u0440\u0443\u043F\u043F\u044B",
      clickToAdd: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u043D\u0430 \u0444\u0443\u043D\u043A\u0446\u0438\u044E \u0441\u043B\u0435\u0432\u0430 \u0447\u0442\u043E\u0431\u044B \u0434\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432 \u0433\u0440\u0443\u043F\u043F\u0443",
      nextStep: "\u0414\u0430\u043B\u0435\u0435",
      previousStep: "\u041D\u0430\u0437\u0430\u0434",
      setNameAndIcon: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C \u0438\u043C\u044F \u0438 \u0437\u043D\u0430\u0447\u043E\u043A",
      groupName: "\u0418\u043C\u044F \u0433\u0440\u0443\u043F\u043F\u044B",
      groupNameDesc: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0438\u043C\u044F \u0434\u043B\u044F \u0433\u0440\u0443\u043F\u043F\u044B",
      groupNamePlaceholder: "\u043D\u0430\u043F\u0440.: \u0427\u0430\u0441\u0442\u044B\u0435 \u0438\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B",
      customIcon: "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0439 \u0437\u043D\u0430\u0447\u043E\u043A (\u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E)",
      clickSelectAll: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u0447\u0442\u043E\u0431\u044B \u0432\u044B\u0431\u0440\u0430\u0442\u044C \u0432\u0441\u0435",
      selectAll: "\u0412\u044B\u0431\u0440\u0430\u0442\u044C \u0432\u0441\u0435",
      pleaseEnterName: "\u041F\u043E\u0436\u0430\u043B\u0443\u0439\u0441\u0442\u0430 \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043C\u044F \u0433\u0440\u0443\u043F\u043F\u044B",
      pleaseSelectOne: "\u041F\u043E\u0436\u0430\u043B\u0443\u0439\u0441\u0442\u0430 \u0432\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0445\u043E\u0442\u044F \u0431\u044B \u043E\u0434\u043D\u0443 \u0444\u0443\u043D\u043A\u0446\u0438\u044E",
      groupCreated: "\u0413\u0440\u0443\u043F\u043F\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0430",
      groupUpdated: "\u0413\u0440\u0443\u043F\u043F\u0430 \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430",
      usageInstructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043A\u0446\u0438\u044F \u043F\u043E \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u043D\u0438\u044E",
      instruction1: '\u041D\u0430\u0436\u043C\u0438\u0442\u0435 "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0433\u0440\u0443\u043F\u043F\u0443" \u0447\u0442\u043E\u0431\u044B \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u0438\u0442\u044C \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0437\u043D\u0430\u0447\u043A\u043E\u0432 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438 \u0432 \u043E\u0434\u0438\u043D',
      instruction2: "\u041D\u0430\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430 \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u0435\u043D\u043D\u044B\u0439 \u0437\u043D\u0430\u0447\u043E\u043A \u0447\u0442\u043E\u0431\u044B \u043F\u043E\u043A\u0430\u0437\u0430\u0442\u044C \u043C\u0435\u043D\u044E \u0444\u0443\u043D\u043A\u0446\u0438\u0439",
      instruction3: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u043D\u0430 \u044D\u043B\u0435\u043C\u0435\u043D\u0442 \u0444\u0443\u043D\u043A\u0446\u0438\u0438 \u0447\u0442\u043E\u0431\u044B \u0430\u043A\u0442\u0438\u0432\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0441\u043E\u043E\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u044E\u0449\u0443\u044E \u0444\u0443\u043D\u043A\u0446\u0438\u044E",
      instruction4: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u043D\u0430 \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u0435\u043D\u043D\u044B\u0439 \u0437\u043D\u0430\u0447\u043E\u043A \u0447\u0442\u043E\u0431\u044B \u043D\u0430\u043F\u0440\u044F\u043C\u0443\u044E \u043E\u0442\u043A\u0440\u044B\u0442\u044C \u043F\u0435\u0440\u0432\u0443\u044E \u0444\u0443\u043D\u043A\u0446\u0438\u044E",
      language: "\u042F\u0437\u044B\u043A",
      languageDesc: "\u0412\u044B\u0431\u0440\u0430\u0442\u044C \u044F\u0437\u044B\u043A \u0438\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E \u0441\u043B\u0435\u0434\u0443\u0435\u0442 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430\u043C Obsidian)",
      auto: "\u0410\u0432\u0442\u043E",
      assigned: "\u041D\u0430\u0437\u043D\u0430\u0447\u0435\u043D\u043E",
      cancel: "\u041E\u0442\u043C\u0435\u043D\u0430",
      save: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C",
      noPreview: "\u041D\u0435\u0442 \u043F\u0440\u0435\u0434\u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430",
      svgPlaceholder: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 SVG-\u043A\u043E\u0434 (\u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E)",
      examples: "\u041F\u0440\u0438\u043C\u0435\u0440\u044B:",
      folder: "\u041F\u0430\u043F\u043A\u0430",
      star: "\u0417\u0432\u0435\u0437\u0434\u0430",
      grid: "\u0421\u0435\u0442\u043A\u0430"
    },
    es: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "Fusionar m\xFAltiples iconos de la barra lateral del mismo plugin en uno, al pasar el mouse mostrar men\xFA de funciones",
      enableOrganizer: "Activar organizaci\xF3n de barra lateral",
      enableOrganizerDesc: "Activar/desactivar funci\xF3n de fusi\xF3n de iconos de barra lateral",
      blurEffect: "Efecto de desenfoque",
      blurEffectDesc: "A\xF1adir efecto de desenfoque de fondo al men\xFA emergente",
      blurIntensity: "Intensidad del desenfoque",
      blurIntensityDesc: "Ajustar nivel de desenfoque de fondo (actual: {value}px)",
      refreshSidebar: "Actualizar barra lateral",
      refreshSidebarDesc: "Redetectar y organizar iconos de barra lateral",
      refreshBtn: "Actualizar",
      refreshNotice: "Barra lateral actualizada",
      customGroups: "Grupos personalizados",
      customGroupsDesc: "Crear grupos personalizados, seleccionar manualmente funciones a fusionar",
      createGroup: "Crear grupo",
      editGroup: "Editar",
      deleteGroup: "Eliminar",
      groupDeleted: "Grupo eliminado",
      actionCount: "{count} funciones",
      default: "Predeterminado",
      autoGroups: "Grupos auto-detectados",
      autoGroupsDesc: "Los siguientes plugins tienen m\xFAltiples funciones en la barra lateral y se agrupan autom\xE1ticamente. Edite para personalizar.",
      autoGroupBadge: "Auto",
      createGroupTitle: "Crear grupo",
      editGroupTitle: "Editar grupo",
      selectFunctions: "Seleccionar funciones",
      selectFunctionsDesc: "Clic en funci\xF3n para a\xF1adir al grupo, clic en t\xEDtulo del grupo para seleccionar todo",
      availableFunctions: "Funciones disponibles",
      groupFunctions: "Funciones del grupo",
      clickToAdd: "Clic en funci\xF3n izquierda para a\xF1adir al grupo",
      nextStep: "Siguiente",
      previousStep: "Anterior",
      setNameAndIcon: "Establecer nombre e icono",
      groupName: "Nombre del grupo",
      groupNameDesc: "Especificar un nombre para el grupo",
      groupNamePlaceholder: "ej: Herramientas comunes",
      customIcon: "Icono personalizado (Opcional)",
      clickSelectAll: "Clic para seleccionar todo",
      selectAll: "Seleccionar todo",
      pleaseEnterName: "Por favor ingrese nombre del grupo",
      pleaseSelectOne: "Por favor seleccione al menos una funci\xF3n",
      groupCreated: "Grupo creado",
      groupUpdated: "Grupo actualizado",
      usageInstructions: "Instrucciones de uso",
      instruction1: 'Clic en "Crear grupo" para fusionar m\xFAltiples iconos de barra lateral en uno',
      instruction2: "Pasar mouse sobre icono fusionado para mostrar men\xFA de funciones",
      instruction3: "Clic en elemento de funci\xF3n para activar funci\xF3n correspondiente",
      instruction4: "Clic en icono fusionado para abrir directamente la primera funci\xF3n",
      language: "Idioma",
      languageDesc: "Seleccionar idioma de interfaz del plugin (por defecto sigue configuraci\xF3n de Obsidian)",
      auto: "Auto",
      assigned: "Asignado",
      cancel: "Cancelar",
      save: "Guardar",
      noPreview: "Sin vista previa",
      svgPlaceholder: "Introducir c\xF3digo SVG (opcional)",
      examples: "Ejemplos:",
      folder: "Carpeta",
      star: "Estrella",
      grid: "Cuadr\xEDcula"
    },
    fr: {
      pluginName: "Sidebar Organizer",
      pluginDesc: "Fusionner plusieurs ic\xF4nes de barre lat\xE9rale du m\xEAme plugin en une seule, survol pour afficher le menu des fonctions",
      enableOrganizer: "Activer l'organisation de la barre lat\xE9rale",
      enableOrganizerDesc: "Activer/d\xE9sactiver la fonction de fusion des ic\xF4nes de barre lat\xE9rale",
      blurEffect: "Effet de flou",
      blurEffectDesc: "Ajouter un effet de flou en arri\xE8re-plan au menu contextuel",
      blurIntensity: "Intensit\xE9 du flou",
      blurIntensityDesc: "Ajuster le niveau de flou de l'arri\xE8re-plan (actuel: {value}px)",
      refreshSidebar: "Actualiser la barre lat\xE9rale",
      refreshSidebarDesc: "Red\xE9tecter et organiser les ic\xF4nes de barre lat\xE9rale",
      refreshBtn: "Actualiser",
      refreshNotice: "Barre lat\xE9rale actualis\xE9e",
      customGroups: "Groupes personnalis\xE9s",
      customGroupsDesc: "Cr\xE9er des groupes personnalis\xE9s, s\xE9lectionner manuellement les fonctions \xE0 fusionner",
      createGroup: "Cr\xE9er un groupe",
      editGroup: "Modifier",
      deleteGroup: "Supprimer",
      groupDeleted: "Groupe supprim\xE9",
      actionCount: "{count} fonctions",
      default: "Par d\xE9faut",
      autoGroups: "Groupes auto-d\xE9tect\xE9s",
      autoGroupsDesc: "Les plugins suivants ont plusieurs fonctions de barre lat\xE9rale et sont regroup\xE9s automatiquement. Modifiez pour personnaliser.",
      autoGroupBadge: "Auto",
      createGroupTitle: "Cr\xE9er un groupe",
      editGroupTitle: "Modifier le groupe",
      selectFunctions: "S\xE9lectionner les fonctions",
      selectFunctionsDesc: "Cliquer sur une fonction pour l'ajouter au groupe, cliquer sur le titre du groupe pour tout s\xE9lectionner",
      availableFunctions: "Fonctions disponibles",
      groupFunctions: "Fonctions du groupe",
      clickToAdd: "Cliquer sur les fonctions \xE0 gauche pour les ajouter au groupe",
      nextStep: "Suivant",
      previousStep: "Pr\xE9c\xE9dent",
      setNameAndIcon: "D\xE9finir le nom et l'ic\xF4ne",
      groupName: "Nom du groupe",
      groupNameDesc: "Sp\xE9cifier un nom pour le groupe",
      groupNamePlaceholder: "ex: Outils courants",
      customIcon: "Ic\xF4ne personnalis\xE9e (Optionnel)",
      clickSelectAll: "Cliquer pour tout s\xE9lectionner",
      selectAll: "Tout s\xE9lectionner",
      pleaseEnterName: "Veuillez entrer un nom de groupe",
      pleaseSelectOne: "Veuillez s\xE9lectionner au moins une fonction",
      groupCreated: "Groupe cr\xE9\xE9",
      groupUpdated: "Groupe mis \xE0 jour",
      usageInstructions: "Instructions d'utilisation",
      instruction1: 'Cliquer sur "Cr\xE9er un groupe" pour fusionner plusieurs ic\xF4nes de barre lat\xE9rale en une seule',
      instruction2: "Survoler l'ic\xF4ne fusionn\xE9e pour afficher le menu des fonctions",
      instruction3: "Cliquer sur un \xE9l\xE9ment de fonction pour activer la fonction correspondante",
      instruction4: "Cliquer sur l'ic\xF4ne fusionn\xE9e pour ouvrir directement la premi\xE8re fonction",
      language: "Langue",
      languageDesc: "S\xE9lectionner la langue de l'interface du plugin (par d\xE9faut suit les param\xE8tres d'Obsidian)",
      auto: "Auto",
      assigned: "Attribu\xE9",
      cancel: "Annuler",
      save: "Enregistrer",
      noPreview: "Aucun aper\xE7u",
      svgPlaceholder: "Entrer le code SVG (optionnel)",
      examples: "Exemples:",
      folder: "Dossier",
      star: "\xC9toile",
      grid: "Grille"
    }
  };
  function getLanguageCode(lang) {
    if (lang.startsWith("zh"))
      return "zh";
    if (lang.startsWith("en"))
      return "en";
    if (lang.startsWith("ja"))
      return "ja";
    if (lang.startsWith("ko"))
      return "ko";
    if (lang.startsWith("de"))
      return "de";
    if (lang.startsWith("ru"))
      return "ru";
    if (lang.startsWith("es"))
      return "es";
    if (lang.startsWith("fr"))
      return "fr";
    return "en";
  }
  function getPluginLanguage(settings, locale) {
    if (settings.language === "auto") {
      return getLanguageCode(locale || "en");
    }
    return settings.language;
  }
  function translate(lang, key, params) {
    const table = translations[lang] || translations["en"];
    let text = table[key] || translations["en"][key] || key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        text = text.replace(`{${k}}`, String(v));
      }
    }
    return text;
  }

  // src/sidebar.ts
  function setSvgContent(element, svgContent) {
    element.empty();
    if (!svgContent || !svgContent.includes("<svg"))
      return;
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgContent.trim(), "image/svg+xml");
    const svg = doc.querySelector("svg");
    if (svg) {
      element.appendChild(svg);
    }
  }
  function parseSvg(svgContent) {
    if (!svgContent || !svgContent.includes("<svg"))
      return null;
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgContent.trim(), "image/svg+xml");
    return doc.querySelector("svg");
  }
  function sanitizeSvgColors(svg) {
    try {
      const keepValues = /* @__PURE__ */ new Set(["none", "currentColor"]);
      const colorAttrs = ["fill", "stroke"];
      svg.querySelectorAll("*").forEach((el) => {
        colorAttrs.forEach((attr) => {
          const value = el.getAttribute(attr);
          if (value && !keepValues.has(value)) {
            if (value.startsWith("#") || value.startsWith("rgb") || value.startsWith("hsl") || /^[a-zA-Z]+$/.test(value)) {
              el.setAttribute(attr, "currentColor");
            }
          }
        });
      });
      const hasFill = svg.querySelector("[fill]");
      const hasStroke = svg.querySelector("[stroke]");
      if (!hasFill && !hasStroke) {
        svg.setAttribute("fill", "currentColor");
      }
    } catch (e) {
      console.warn("Sidebar Organizer: failed to sanitize SVG colors", e);
    }
  }

  // src/settings.ts
  var import_obsidian2 = __require("obsidian");

  // src/modal.ts
  var import_obsidian = __require("obsidian");
  var SimpleGroupModal = class extends import_obsidian.Modal {
    constructor(app, plugin, onSave, existingGroup = null) {
      super(app);
      this.step = 1;
      this.selectedActions = /* @__PURE__ */ new Set();
      this.groupName = "";
      this.groupIcon = "";
      this.allActions = [];
      this.plugin = plugin;
      this.onSave = onSave;
      this.existingGroup = existingGroup;
      if (existingGroup) {
        this.selectedActions = new Set(existingGroup.actionIds);
        this.groupName = existingGroup.name;
        this.groupIcon = existingGroup.icon || "";
      }
    }
    t(key, params) {
      var _a;
      const vault = this.app.vault;
      const lang = getPluginLanguage(this.plugin.settings, (_a = vault == null ? void 0 : vault.config) == null ? void 0 : _a.locale);
      return translate(lang, key, params);
    }
    onOpen() {
      const { contentEl } = this;
      contentEl.empty();
      this.allActions = this.plugin.getAllActions();
      this.renderStep1();
    }
    renderStep1() {
      const { contentEl } = this;
      contentEl.empty();
      new import_obsidian.Setting(contentEl).setName(this.existingGroup ? `${this.t("editGroupTitle")} - ${this.t("selectFunctions")}` : `${this.t("createGroupTitle")} - ${this.t("selectFunctions")}`).setHeading();
      contentEl.createEl("p", {
        text: this.t("selectFunctionsDesc"),
        cls: "sidebar-organizer-hint"
      });
      const assignedElsewhere = /* @__PURE__ */ new Set();
      this.plugin.settings.customGroups.forEach((g) => {
        if (this.existingGroup && g.id === this.existingGroup.id)
          return;
        g.actionIds.forEach((id) => assignedElsewhere.add(id));
      });
      const pluginGroups = /* @__PURE__ */ new Map();
      for (const action of this.allActions) {
        const isAssignedElsewhere = assignedElsewhere.has(action.actionId);
        const isSelected = this.selectedActions.has(action.actionId);
        if (isAssignedElsewhere && !isSelected)
          continue;
        if (!pluginGroups.has(action.pluginName)) {
          pluginGroups.set(action.pluginName, []);
        }
        pluginGroups.get(action.pluginName).push(action);
      }
      const container = contentEl.createDiv("simple-group-container");
      const leftPanel = container.createDiv("panel-left");
      new import_obsidian.Setting(leftPanel).setName(this.t("availableFunctions")).setHeading();
      this.availableContainer = leftPanel.createDiv("actions-list");
      for (const [pluginName, actions] of pluginGroups) {
        const groupEl = this.availableContainer.createDiv("action-group");
        const groupHeader = groupEl.createDiv("action-group-header");
        const allSelected = actions.every((a) => this.selectedActions.has(a.actionId));
        if (allSelected && actions.length > 0) {
          groupHeader.classList.add("all-selected");
        }
        groupHeader.createSpan("group-title").textContent = `${pluginName} (${actions.length})`;
        groupHeader.createSpan("select-all-hint").textContent = this.t("clickSelectAll");
        groupHeader.addEventListener("click", (e) => {
          e.stopPropagation();
          const allInGroup = actions.every((a) => this.selectedActions.has(a.actionId));
          if (allInGroup) {
            actions.forEach((a) => this.selectedActions.delete(a.actionId));
          } else {
            actions.forEach((a) => this.selectedActions.add(a.actionId));
          }
          groupActions.querySelectorAll(".action-item-draggable").forEach((el) => {
            const aid = el.getAttribute("data-action-id");
            if (aid && this.selectedActions.has(aid)) {
              el.classList.add("in-group");
            } else {
              el.classList.remove("in-group");
            }
          });
          groupHeader.classList.toggle("all-selected", !allInGroup);
          this.updateSelectedList(assignedElsewhere);
        });
        const groupActions = groupEl.createDiv("group-actions");
        for (const action of actions) {
          const isSelected = this.selectedActions.has(action.actionId);
          const itemEl = groupActions.createDiv("action-item-draggable");
          itemEl.setAttribute("data-action-id", action.actionId);
          if (isSelected)
            itemEl.classList.add("in-group");
          const iconSpan = itemEl.createSpan("item-icon");
          setSvgContent(iconSpan, action.icon);
          const nameSpan = itemEl.createSpan("item-name");
          nameSpan.textContent = action.actionName;
          itemEl.addEventListener("click", (e) => {
            e.stopPropagation();
            if (this.selectedActions.has(action.actionId)) {
              this.selectedActions.delete(action.actionId);
              itemEl.classList.remove("in-group");
            } else {
              this.selectedActions.add(action.actionId);
              itemEl.classList.add("in-group");
            }
            this.updateSelectedList(assignedElsewhere);
            const allNowSelected = actions.every((a) => this.selectedActions.has(a.actionId));
            if (allNowSelected) {
              groupHeader.classList.add("all-selected");
            } else {
              groupHeader.classList.remove("all-selected");
            }
          });
        }
      }
      const rightPanel = container.createDiv("panel-right");
      new import_obsidian.Setting(rightPanel).setName(this.t("groupFunctions")).setHeading();
      this.selectedContainer = rightPanel.createDiv("actions-list selected-list");
      this.updateSelectedList(assignedElsewhere);
      const buttonContainer = contentEl.createDiv("modal-button-container");
      buttonContainer.createEl("button", { text: this.t("cancel") }).addEventListener("click", () => this.close());
      buttonContainer.createEl("button", { text: this.t("nextStep"), cls: "mod-cta" }).addEventListener("click", () => {
        if (this.selectedActions.size === 0) {
          new import_obsidian.Notice(this.t("pleaseSelectOne"));
          return;
        }
        this.renderStep2();
      });
    }
    updateSelectedList(assignedElsewhere) {
      this.selectedContainer.empty();
      const selectedActions = this.allActions.filter((a) => this.selectedActions.has(a.actionId));
      if (selectedActions.length === 0) {
        this.selectedContainer.createEl("p", {
          text: this.t("clickToAdd"),
          cls: "empty-hint"
        });
        return;
      }
      for (const action of selectedActions) {
        const itemEl = this.selectedContainer.createDiv("selected-action-item");
        itemEl.setAttribute("data-action-id", action.actionId);
        const iconSpan = itemEl.createSpan("item-icon");
        setSvgContent(iconSpan, action.icon);
        const nameSpan = itemEl.createSpan("item-name");
        nameSpan.textContent = action.actionName;
        const removeBtn = itemEl.createSpan("remove-btn");
        removeBtn.textContent = "\xD7";
        removeBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.selectedActions.delete(action.actionId);
          this.updateSelectedList(assignedElsewhere);
          this.availableContainer.querySelectorAll(".action-item-draggable").forEach((el) => {
            if (el.getAttribute("data-action-id") === action.actionId) {
              el.classList.remove("in-group");
            }
          });
          this.availableContainer.querySelectorAll(".action-group-header").forEach((header) => {
            const parent = header.closest(".action-group");
            if (!parent)
              return;
            const items = parent.querySelectorAll(".action-item-draggable");
            const allSelected = Array.from(items).every(
              (el) => this.selectedActions.has(el.getAttribute("data-action-id") || "")
            );
            header.classList.toggle("all-selected", allSelected);
          });
        });
      }
    }
    renderStep2() {
      const { contentEl } = this;
      contentEl.empty();
      new import_obsidian.Setting(contentEl).setName(this.existingGroup ? `${this.t("editGroupTitle")} - ${this.t("setNameAndIcon")}` : `${this.t("createGroupTitle")} - ${this.t("setNameAndIcon")}`).setHeading();
      new import_obsidian.Setting(contentEl).setName(this.t("groupName")).setDesc(this.t("groupNameDesc")).addText((text) => {
        this.nameInput = text.inputEl;
        text.setPlaceholder(this.t("groupNamePlaceholder"));
        text.setValue(this.groupName);
        text.onChange((value) => {
          this.groupName = value;
        });
      });
      new import_obsidian.Setting(contentEl).setName(this.t("customIcon")).setHeading();
      const iconSection = contentEl.createDiv("icon-section");
      this.previewEl = iconSection.createDiv("icon-preview-small");
      this.updatePreview();
      const inputSection = iconSection.createDiv("icon-input-section");
      this.iconInput = inputSection.createEl("textarea", {
        attr: {
          placeholder: this.t("svgPlaceholder"),
          rows: "4",
          class: "svg-input-small"
        }
      });
      this.iconInput.value = this.groupIcon;
      this.iconInput.addEventListener("input", () => {
        this.groupIcon = this.iconInput.value;
        this.updatePreview();
      });
      const examplesSection = contentEl.createDiv("icon-examples");
      examplesSection.createEl("span", { text: this.t("examples") });
      const examples = [
        { name: this.t("folder"), svg: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path></svg>' },
        { name: this.t("star"), svg: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>' },
        { name: this.t("grid"), svg: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>' }
      ];
      for (const example of examples) {
        examplesSection.createEl("button", { text: example.name }).addEventListener("click", () => {
          this.iconInput.value = example.svg;
          this.groupIcon = example.svg;
          this.updatePreview();
        });
      }
      const buttonContainer = contentEl.createDiv("modal-button-container");
      buttonContainer.createEl("button", { text: this.t("previousStep") }).addEventListener("click", () => this.renderStep1());
      buttonContainer.createEl("button", { text: this.t("cancel") }).addEventListener("click", () => this.close());
      buttonContainer.createEl("button", { text: this.t("save"), cls: "mod-cta" }).addEventListener("click", () => {
        void (async () => {
          const name = this.nameInput.value.trim();
          if (!name) {
            new import_obsidian.Notice(this.t("pleaseEnterName"));
            return;
          }
          if (this.selectedActions.size === 0) {
            new import_obsidian.Notice(this.t("pleaseSelectOne"));
            return;
          }
          if (this.existingGroup) {
            const group = this.plugin.settings.customGroups.find((g) => g.id === this.existingGroup.id);
            if (group) {
              group.name = name;
              group.icon = this.groupIcon.trim();
              group.actionIds = Array.from(this.selectedActions);
              if (group.autoGroup) {
                delete group.autoGroup;
              }
            } else {
              const newGroup = {
                id: `custom-${Date.now()}`,
                name,
                icon: this.groupIcon.trim(),
                actionIds: Array.from(this.selectedActions),
                order: this.plugin.settings.customGroups.length
              };
              this.plugin.settings.customGroups.push(newGroup);
            }
          } else {
            const newGroup = {
              id: `custom-${Date.now()}`,
              name,
              icon: this.groupIcon.trim(),
              actionIds: Array.from(this.selectedActions),
              order: this.plugin.settings.customGroups.length
            };
            this.plugin.settings.customGroups.push(newGroup);
          }
          await this.plugin.saveSettings();
          this.close();
          this.onSave();
          new import_obsidian.Notice(this.existingGroup ? this.t("groupUpdated") : this.t("groupCreated"));
        })();
      });
    }
    updatePreview() {
      setSvgContent(this.previewEl, this.groupIcon);
      if (!this.groupIcon || !this.groupIcon.includes("<svg")) {
        this.previewEl.createEl("span", {
          text: this.t("default"),
          cls: "default-icon-hint"
        });
      }
    }
    onClose() {
      const { contentEl } = this;
      contentEl.empty();
    }
  };

  // src/settings.ts
  var SidebarOrganizerSettingTab = class extends import_obsidian2.PluginSettingTab {
    constructor(app, plugin) {
      super(app, plugin);
      this.plugin = plugin;
    }
    t(key, params) {
      var _a;
      const vault = this.app.vault;
      const lang = getPluginLanguage(this.plugin.settings, (_a = vault == null ? void 0 : vault.config) == null ? void 0 : _a.locale);
      return translate(lang, key, params);
    }
    display() {
      const { containerEl } = this;
      containerEl.empty();
      new import_obsidian2.Setting(containerEl).setName(this.t("pluginName")).setHeading();
      containerEl.createEl("p", {
        text: this.t("pluginDesc"),
        cls: "sidebar-organizer-desc"
      });
      new import_obsidian2.Setting(containerEl).setName(this.t("language")).setDesc(this.t("languageDesc")).addDropdown((dropdown) => dropdown.addOption("auto", this.t("auto")).addOption("zh", "\u4E2D\u6587").addOption("en", "English").addOption("ja", "\u65E5\u672C\u8A9E").addOption("ko", "\uD55C\uAD6D\uC5B4").addOption("de", "Deutsch").addOption("ru", "\u0420\u0443\u0441\u0441\u043A\u0438\u0439").addOption("es", "Espa\xF1ol").addOption("fr", "Fran\xE7ais").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian2.Setting(containerEl).setName(this.t("enableOrganizer")).setDesc(this.t("enableOrganizerDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
        this.plugin.applyOrganizerState();
      }));
      new import_obsidian2.Setting(containerEl).setName(this.t("blurEffect")).setDesc(this.t("blurEffectDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.blurEffect).onChange(async (value) => {
        this.plugin.settings.blurEffect = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(containerEl).setName(this.t("blurIntensity")).setDesc(this.t("blurIntensityDesc", { value: this.plugin.settings.blurIntensity })).addSlider((slider) => slider.setValue(this.plugin.settings.blurIntensity).setLimits(0, 30, 1).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.blurIntensity = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(containerEl).setName(this.t("refreshSidebar")).setDesc(this.t("refreshSidebarDesc")).addButton((btn) => btn.setButtonText(this.t("refreshBtn")).onClick(() => {
        this.plugin.restoreOriginalIcons();
        this.plugin.loadInstalledPlugins();
        this.plugin.organizeSidebars();
        this.display();
        new import_obsidian2.Notice(this.t("refreshNotice"));
      }));
      new import_obsidian2.Setting(containerEl).setName(this.t("customGroups")).setHeading();
      containerEl.createEl("p", {
        text: this.t("customGroupsDesc"),
        cls: "sidebar-organizer-hint"
      });
      new import_obsidian2.Setting(containerEl).setName(this.t("createGroup")).setDesc(this.t("customGroupsDesc")).addButton((btn) => btn.setButtonText(this.t("createGroup")).onClick(() => {
        const modal = new SimpleGroupModal(this.app, this.plugin, () => {
          this.plugin.restoreOriginalIcons();
          this.plugin.organizeSidebars();
          this.display();
        });
        modal.open();
      }));
      if (this.plugin.settings.customGroups.length > 0) {
        const groupsContainer = containerEl.createDiv("sidebar-organizer-custom-groups");
        const sortedGroups = [...this.plugin.settings.customGroups].sort((a, b) => a.order - b.order);
        for (const group of sortedGroups) {
          const groupEl = groupsContainer.createDiv("sidebar-organizer-custom-group-item");
          const infoEl = groupEl.createDiv("group-header");
          const iconEl = infoEl.createDiv("group-icon");
          if (group.icon) {
            setSvgContent(iconEl, group.icon);
          } else {
            iconEl.createEl("span", { text: "\u{1F4CB}", cls: "default-group-icon" });
          }
          const nameEl = infoEl.createDiv("group-title");
          nameEl.textContent = group.name;
          const countEl = infoEl.createDiv("group-count");
          countEl.textContent = this.t("actionCount", { count: group.actionIds.length });
          const actionsEl = infoEl.createDiv("group-actions");
          actionsEl.createEl("button", { text: this.t("editGroup") }).addEventListener("click", () => {
            const modal = new SimpleGroupModal(this.app, this.plugin, () => {
              this.plugin.restoreOriginalIcons();
              this.plugin.organizeSidebars();
              this.display();
            }, group);
            modal.open();
          });
          actionsEl.createEl("button", { text: this.t("deleteGroup"), cls: "mod-warning" }).addEventListener("click", () => {
            void (async () => {
              this.plugin.settings.customGroups = this.plugin.settings.customGroups.filter((g) => g.id !== group.id);
              await this.plugin.saveSettings();
              this.plugin.restoreOriginalIcons();
              this.plugin.organizeSidebars();
              this.display();
              new import_obsidian2.Notice(this.t("groupDeleted"));
            })();
          });
        }
      }
      const allSidebarActions = this.plugin.getAllActions();
      const assignedToCustom = /* @__PURE__ */ new Set();
      this.plugin.settings.customGroups.forEach((g) => {
        g.actionIds.forEach((id) => assignedToCustom.add(id));
      });
      const remainingActionsDisplay = allSidebarActions.filter((a) => !assignedToCustom.has(a.actionId));
      const autoPluginMap = /* @__PURE__ */ new Map();
      for (const action of remainingActionsDisplay) {
        if (!autoPluginMap.has(action.pluginId)) {
          autoPluginMap.set(action.pluginId, []);
        }
        autoPluginMap.get(action.pluginId).push(action);
      }
      const autoGroupsToShow = Array.from(autoPluginMap.entries()).filter(([_, actions]) => actions.length > 1);
      if (autoGroupsToShow.length > 0) {
        new import_obsidian2.Setting(containerEl).setName(this.t("autoGroups")).setHeading();
        containerEl.createEl("p", {
          text: this.t("autoGroupsDesc"),
          cls: "sidebar-organizer-hint"
        });
        const autoContainer = containerEl.createDiv("sidebar-organizer-custom-groups");
        for (const [pluginId, actions] of autoGroupsToShow) {
          const groupEl = autoContainer.createDiv("sidebar-organizer-custom-group-item");
          const infoEl = groupEl.createDiv("group-header");
          const autoBadge = infoEl.createDiv("auto-group-badge");
          autoBadge.textContent = this.t("autoGroupBadge");
          const iconEl = infoEl.createDiv("group-icon");
          setSvgContent(iconEl, actions[0].icon);
          const nameEl = infoEl.createDiv("group-title");
          nameEl.textContent = actions[0].pluginName;
          const countEl = infoEl.createDiv("group-count");
          countEl.textContent = this.t("actionCount", { count: actions.length });
          const actionsEl = infoEl.createDiv("group-actions");
          actionsEl.createEl("button", { text: this.t("editGroup") }).addEventListener("click", () => {
            const tempGroup = {
              id: `auto-temp-${Date.now()}`,
              name: actions[0].pluginName,
              icon: "",
              actionIds: actions.map((a) => a.actionId),
              order: this.plugin.settings.customGroups.length,
              autoGroup: true
            };
            const modal = new SimpleGroupModal(this.app, this.plugin, () => {
              this.plugin.restoreOriginalIcons();
              this.plugin.organizeSidebars();
              this.display();
            }, tempGroup);
            modal.open();
          });
        }
      }
      new import_obsidian2.Setting(containerEl).setName(this.t("usageInstructions")).setHeading();
      const usageList = containerEl.createEl("ul");
      usageList.createEl("li", { text: this.t("instruction1") });
      usageList.createEl("li", { text: this.t("instruction2") });
      usageList.createEl("li", { text: this.t("instruction3") });
      usageList.createEl("li", { text: this.t("instruction4") });
    }
  };

  // src/main.ts
  var SidebarOrganizerPlugin = class extends import_obsidian3.Plugin {
    constructor() {
      super(...arguments);
      this.installedPlugins = /* @__PURE__ */ new Map();
      this.isOrganizing = false;
      this.popupEl = null;
      this.hideTimeout = null;
      this.showTimeout = null;
      this.boundElements = /* @__PURE__ */ new Map();
      this.popupMouseEnterHandler = null;
      this.popupMouseLeaveHandler = null;
      this.mutationObserver = null;
      this.observerDebounceTimer = null;
      this.hoveredIconEl = null;
      this.popupHovered = false;
      this.isHiding = false;
      this.currentPopupAnchor = null;
    }
    t(key, params) {
      const vaultConfig = this.app.vault.config;
      const lang = getPluginLanguage(this.settings, vaultConfig == null ? void 0 : vaultConfig.locale);
      return translate(lang, key, params);
    }
    async onload() {
      await this.loadSettings();
      this.addSettingTab(new SidebarOrganizerSettingTab(this.app, this));
      this.addCommand({
        id: "toggle",
        name: "Toggle",
        callback: () => {
          this.settings.enabled = !this.settings.enabled;
          void this.saveSettings();
          this.applyOrganizerState();
          new import_obsidian3.Notice(`Sidebar Organizer ${this.settings.enabled ? "enabled" : "disabled"}`);
        }
      });
      this.addCommand({
        id: "refresh",
        name: "Refresh",
        callback: () => {
          this.restoreOriginalIcons();
          this.loadInstalledPlugins();
          this.organizeSidebars();
          new import_obsidian3.Notice("Sidebar refreshed");
        }
      });
      this.app.workspace.onLayoutReady(() => {
        this.loadInstalledPlugins();
        setTimeout(() => {
          if (this.settings.enabled) {
            this.organizeSidebars();
          }
          this.startMutationObserver();
        }, 1e3);
      });
    }
    onunload() {
      this.stopMutationObserver();
      this.cleanupPopupHandlers();
      this.cleanupAllListeners();
      if (this.showTimeout) {
        clearTimeout(this.showTimeout);
        this.showTimeout = null;
      }
      this.restoreOriginalIcons();
    }
    startMutationObserver() {
      this.stopMutationObserver();
      this.mutationObserver = new MutationObserver(() => {
        if (this.observerDebounceTimer) {
          clearTimeout(this.observerDebounceTimer);
        }
        this.observerDebounceTimer = window.setTimeout(() => {
          if (this.settings.enabled) {
            try {
              this.loadInstalledPlugins();
              this.organizeSidebars();
            } catch (e) {
              console.error("Sidebar Organizer: error during mutation re-scan", e);
            }
          }
        }, 500);
      });
      ["left", "right"].forEach((side) => {
        const ribbon = document.querySelector(`.workspace-ribbon.mod-${side}`);
        if (ribbon) {
          this.mutationObserver.observe(ribbon, { childList: true, subtree: true });
        }
      });
    }
    stopMutationObserver() {
      if (this.observerDebounceTimer) {
        clearTimeout(this.observerDebounceTimer);
        this.observerDebounceTimer = null;
      }
      if (this.mutationObserver) {
        this.mutationObserver.disconnect();
        this.mutationObserver = null;
      }
    }
    cleanupPopupHandlers() {
      if (this.popupMouseEnterHandler && this.popupEl) {
        this.popupEl.removeEventListener("mouseenter", this.popupMouseEnterHandler);
      }
      if (this.popupMouseLeaveHandler && this.popupEl) {
        this.popupEl.removeEventListener("mouseleave", this.popupMouseLeaveHandler);
      }
      this.popupMouseEnterHandler = null;
      this.popupMouseLeaveHandler = null;
    }
    cleanupAllListeners() {
      for (const [el, handlers] of this.boundElements) {
        el.removeEventListener("mouseenter", handlers.mouseEnter);
        el.removeEventListener("mouseleave", handlers.mouseLeave);
        el.removeAttribute("data-popup-bound");
      }
      this.boundElements.clear();
      this.cleanupPopupHandlers();
    }
    async loadSettings() {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    }
    async saveSettings() {
      await this.saveData(this.settings);
    }
    loadInstalledPlugins() {
      this.installedPlugins.clear();
      const pluginsContainer = this.app.plugins;
      const plugins = pluginsContainer == null ? void 0 : pluginsContainer.manifests;
      if (plugins) {
        for (const [id, manifest] of Object.entries(plugins)) {
          this.installedPlugins.set(id, manifest);
        }
      }
    }
    applyOrganizerState() {
      if (this.settings.enabled) {
        this.organizeSidebars();
      } else {
        this.restoreOriginalIcons();
      }
    }
    organizeSidebars() {
      if (this.isOrganizing || !this.settings.enabled)
        return;
      this.isOrganizing = true;
      try {
        this.stopMutationObserver();
        this.restoreOriginalIcons();
        this.processRibbon("left");
        this.processRibbon("right");
      } finally {
        this.isOrganizing = false;
        this.startMutationObserver();
      }
    }
    processRibbon(side) {
      const ribbon = document.querySelector(`.workspace-ribbon.mod-${side}`);
      if (!ribbon)
        return;
      const allIcons = ribbon.querySelectorAll(".side-dock-ribbon-action, .clickable-icon, .workspace-ribbon-action");
      const allActions = [];
      const actionMap = /* @__PURE__ */ new Map();
      allIcons.forEach((el) => {
        try {
          const element = el;
          const action = this.identifyAction(element);
          if (!action)
            return;
          allActions.push(action);
          actionMap.set(action.actionId, action);
        } catch (e) {
          console.warn("Sidebar Organizer: failed to process icon", e);
        }
      });
      if (allActions.length === 0)
        return;
      const assignedActionIds = /* @__PURE__ */ new Set();
      const sortedCustomGroups = [...this.settings.customGroups].sort((a, b) => a.order - b.order);
      for (const customGroup of sortedCustomGroups) {
        try {
          const groupActions = customGroup.actionIds.map((id) => actionMap.get(id)).filter((a) => !!a);
          if (groupActions.length === 0)
            continue;
          groupActions.forEach((a) => assignedActionIds.add(a.actionId));
          const mainAction = groupActions[0];
          const otherActions = groupActions.slice(1);
          otherActions.forEach((action) => {
            action.element.classList.add("sidebar-organizer-hidden");
          });
          if (customGroup.icon) {
            this.applyCustomIcon(mainAction.element, customGroup.icon);
          }
          this.bindPopupMenu(mainAction.element, customGroup.name, groupActions);
        } catch (e) {
          console.warn(`Sidebar Organizer: failed to process group "${customGroup.name}"`, e);
        }
      }
      const unassignedActions = allActions.filter((a) => !assignedActionIds.has(a.actionId));
      this.autoGroupRemaining(unassignedActions, assignedActionIds, actionMap);
    }
    autoGroupRemaining(unassignedActions, assignedActionIds, actionMap) {
      const pluginGroups = /* @__PURE__ */ new Map();
      for (const action of unassignedActions) {
        if (!pluginGroups.has(action.pluginId)) {
          pluginGroups.set(action.pluginId, []);
        }
        pluginGroups.get(action.pluginId).push(action);
      }
      for (const [pluginId, actions] of pluginGroups) {
        try {
          if (actions.length <= 1)
            continue;
          actions.forEach((a) => assignedActionIds.add(a.actionId));
          const mainAction = actions[0];
          const otherActions = actions.slice(1);
          otherActions.forEach((action) => {
            action.element.classList.add("sidebar-organizer-hidden");
          });
          this.addBadge(mainAction.element, actions.length);
          const groupName = actions[0].pluginName;
          this.bindPopupMenu(mainAction.element, groupName, actions);
        } catch (e) {
          console.warn(`Sidebar Organizer: failed to auto-group plugin "${pluginId}"`, e);
        }
      }
    }
    addBadge(element, count) {
      if (element.querySelector(".sidebar-organizer-badge"))
        return;
      const badge = document.createElement("span");
      badge.className = "sidebar-organizer-badge";
      badge.textContent = String(count);
      element.appendChild(badge);
    }
    bindPopupMenu(mainElement, title, actions) {
      if (mainElement.hasAttribute("data-popup-bound"))
        return;
      mainElement.setAttribute("data-popup-bound", "true");
      const mouseEnterHandler = () => {
        if (!mainElement.hasAttribute("data-popup-bound"))
          return;
        this.hoveredIconEl = mainElement;
        if (this.hideTimeout) {
          clearTimeout(this.hideTimeout);
          this.hideTimeout = null;
        }
        if (this.popupEl && this.currentPopupAnchor === mainElement)
          return;
        if (this.isHiding)
          return;
        if (this.showTimeout) {
          clearTimeout(this.showTimeout);
        }
        this.showTimeout = window.setTimeout(() => {
          if (!mainElement.hasAttribute("data-popup-bound"))
            return;
          if (this.hoveredIconEl !== mainElement)
            return;
          this.showMenu(mainElement, title, actions);
        }, 180);
      };
      const mouseLeaveHandler = () => {
        if (!mainElement.hasAttribute("data-popup-bound"))
          return;
        this.hoveredIconEl = null;
        if (this.showTimeout) {
          clearTimeout(this.showTimeout);
          this.showTimeout = null;
        }
        this.scheduleHide();
      };
      mainElement.addEventListener("mouseenter", mouseEnterHandler);
      mainElement.addEventListener("mouseleave", mouseLeaveHandler);
      this.boundElements.set(mainElement, { mouseEnter: mouseEnterHandler, mouseLeave: mouseLeaveHandler });
    }
    scheduleHide() {
      if (this.hideTimeout)
        clearTimeout(this.hideTimeout);
      this.hideTimeout = window.setTimeout(() => {
        if (this.popupHovered)
          return;
        if (this.hoveredIconEl)
          return;
        this.hideMenu();
      }, 300);
    }
    showMenu(mainElement, title, actions) {
      if (this.isHiding)
        return;
      if (this.popupEl && this.currentPopupAnchor === mainElement)
        return;
      if (this.popupEl) {
        this.cleanupPopupHandlers();
        this.popupEl.remove();
        this.popupEl = null;
      }
      if (this.hideTimeout) {
        clearTimeout(this.hideTimeout);
        this.hideTimeout = null;
      }
      if (this.showTimeout) {
        clearTimeout(this.showTimeout);
        this.showTimeout = null;
      }
      this.popupEl = document.createElement("div");
      this.popupEl.className = "sidebar-organizer-popup";
      document.body.appendChild(this.popupEl);
      this.currentPopupAnchor = mainElement;
      const popup = this.popupEl;
      this.popupMouseEnterHandler = () => {
        this.popupHovered = true;
        if (this.hideTimeout) {
          clearTimeout(this.hideTimeout);
          this.hideTimeout = null;
        }
      };
      this.popupMouseLeaveHandler = () => {
        this.popupHovered = false;
        this.scheduleHide();
      };
      popup.addEventListener("mouseenter", this.popupMouseEnterHandler);
      popup.addEventListener("mouseleave", this.popupMouseLeaveHandler);
      const bodyEl = popup.createDiv("sidebar-organizer-popup-body");
      const titleEl = bodyEl.createDiv("sidebar-organizer-plugin-name");
      titleEl.textContent = title;
      const listEl = bodyEl.createDiv("sidebar-organizer-actions-list");
      for (const action of actions) {
        const itemEl = listEl.createDiv("sidebar-organizer-action-item");
        const iconEl = itemEl.createDiv("sidebar-organizer-action-icon");
        setSvgContent(iconEl, action.icon);
        const labelEl = itemEl.createDiv("sidebar-organizer-action-label");
        labelEl.textContent = this.extractActionLabel(action.actionName, title);
        itemEl.addEventListener("click", (e) => {
          e.preventDefault();
          e.stopPropagation();
          this.hideMenu();
          action.element.click();
        });
      }
      this.positionPopup(popup, mainElement);
      if (this.settings.blurEffect) {
        popup.classList.add("blur-effect");
        popup.style.setProperty("--blur-amount", `${this.settings.blurIntensity}px`);
      }
      requestAnimationFrame(() => {
        popup.classList.add("visible");
      });
    }
    hideMenu() {
      if (!this.popupEl)
        return;
      this.isHiding = true;
      this.cleanupPopupHandlers();
      const popup = this.popupEl;
      popup.classList.remove("visible");
      popup.classList.add("hiding");
      setTimeout(() => {
        this.popupHovered = false;
        if (popup && popup.parentElement) {
          popup.remove();
        }
        if (this.popupEl === popup) {
          this.popupEl = null;
          this.currentPopupAnchor = null;
        }
        this.isHiding = false;
      }, 250);
    }
    positionPopup(popup, anchor) {
      const rect = anchor.getBoundingClientRect();
      const isLeftSide = rect.left < window.innerWidth / 2;
      const popupWidth = Math.max(popup.offsetWidth, 190);
      if (isLeftSide) {
        popup.style.left = `${rect.right + 8}px`;
        popup.classList.remove("popup-right");
      } else {
        popup.style.left = `${rect.left - popupWidth - 8}px`;
        popup.classList.add("popup-right");
      }
      popup.style.top = `${rect.top}px`;
    }
    identifyAction(element) {
      var _a, _b;
      const ariaLabel = element.getAttribute("aria-label") || "";
      const tooltip = ((_a = element.querySelector(".tooltip")) == null ? void 0 : _a.textContent) || "";
      const dataView = element.getAttribute("data-view") || "";
      const svgIcon = ((_b = element.querySelector("svg")) == null ? void 0 : _b.outerHTML) || "";
      const displayName = ariaLabel || tooltip;
      if (!displayName)
        return null;
      const pluginInfo = this.matchPlugin(displayName, dataView);
      if (!pluginInfo)
        return null;
      const actionId = dataView || displayName.toLowerCase().replace(/\s+/g, "-");
      return {
        element,
        pluginId: pluginInfo.pluginId,
        pluginName: pluginInfo.pluginName,
        actionName: displayName,
        icon: svgIcon,
        actionId
      };
    }
    matchPlugin(displayName, dataView) {
      if (dataView) {
        const parts = dataView.split("-");
        for (let i = 1; i <= Math.min(parts.length, 3); i++) {
          const prefix2 = parts.slice(0, i).join("-");
          for (const [id, manifest] of this.installedPlugins) {
            if (id === prefix2) {
              return { pluginId: id, pluginName: manifest.name };
            }
          }
          for (const [id, manifest] of this.installedPlugins) {
            if (id.startsWith(prefix2) || prefix2.startsWith(id)) {
              return { pluginId: id, pluginName: manifest.name };
            }
          }
        }
        const prefix = dataView.split("-").slice(0, 2).join("-");
        return { pluginId: prefix, pluginName: prefix };
      }
      const nameLower = displayName.toLowerCase();
      for (const [id, manifest] of this.installedPlugins) {
        const pluginName = manifest.name.toLowerCase();
        if (nameLower.includes(pluginName) || pluginName === nameLower) {
          return { pluginId: id, pluginName: manifest.name };
        }
      }
      const firstPart = nameLower.split(/[\s:：\-–—]+/)[0];
      if (firstPart && firstPart.length > 1) {
        for (const [id, manifest] of this.installedPlugins) {
          const pluginName = manifest.name.toLowerCase();
          if (pluginName.includes(firstPart) || firstPart.includes(pluginName)) {
            return { pluginId: id, pluginName: manifest.name };
          }
        }
      }
      const safeId = displayName.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-");
      return {
        pluginId: safeId || "unknown",
        pluginName: displayName
      };
    }
    extractActionLabel(fullName, pluginName) {
      let label = fullName;
      const separators = [":", "\uFF1A", "-", "\u2013", "\u2014", "|"];
      for (const sep of separators) {
        if (fullName.includes(sep)) {
          const parts = fullName.split(sep);
          if (parts.length > 1) {
            label = parts.slice(1).join(sep).trim();
            break;
          }
        }
      }
      return label || fullName;
    }
    applyCustomIcon(element, svgContent) {
      const svgEl = element.querySelector("svg");
      if (svgEl && svgContent) {
        if (!element.hasAttribute("data-original-svg")) {
          element.setAttribute("data-original-svg", svgEl.outerHTML);
        }
        const newSvg = parseSvg(svgContent);
        if (newSvg) {
          if (!newSvg.hasAttribute("viewBox")) {
            newSvg.setAttribute("viewBox", "0 0 24 24");
          }
          sanitizeSvgColors(newSvg);
          newSvg.classList.add("sidebar-organizer-custom-icon");
          newSvg.classList.add("sidebar-organizer-inherit-color");
          svgEl.replaceWith(newSvg);
          return true;
        }
      }
      return false;
    }
    restoreOriginalIcon(element) {
      const originalSvg = element.getAttribute("data-original-svg");
      if (originalSvg) {
        const currentSvg = element.querySelector("svg");
        if (currentSvg) {
          const originalSvgEl = parseSvg(originalSvg);
          if (originalSvgEl) {
            currentSvg.replaceWith(originalSvgEl);
            element.removeAttribute("data-original-svg");
            return true;
          }
        }
      }
      return false;
    }
    restoreOriginalIcons() {
      if (this.hideTimeout) {
        clearTimeout(this.hideTimeout);
        this.hideTimeout = null;
      }
      if (this.showTimeout) {
        clearTimeout(this.showTimeout);
        this.showTimeout = null;
      }
      this.cleanupAllListeners();
      if (this.popupEl) {
        this.popupEl.remove();
        this.popupEl = null;
      }
      this.cleanupPopupHandlers();
      this.popupHovered = false;
      this.isHiding = false;
      this.hoveredIconEl = null;
      this.currentPopupAnchor = null;
      document.querySelectorAll("[data-original-svg]").forEach((el) => {
        try {
          this.restoreOriginalIcon(el);
        } catch (e) {
          console.warn("Sidebar Organizer: failed to restore icon", e);
        }
      });
      document.querySelectorAll(".sidebar-organizer-hidden").forEach((el) => {
        el.classList.remove("sidebar-organizer-hidden");
      });
      document.querySelectorAll(".sidebar-organizer-badge").forEach((el) => {
        try {
          el.remove();
        } catch (e) {
        }
      });
      document.querySelectorAll("[data-popup-bound]").forEach((el) => {
        el.removeAttribute("data-popup-bound");
      });
    }
    getAllActions() {
      const actions = [];
      const seen = /* @__PURE__ */ new Set();
      ["left", "right"].forEach((side) => {
        const ribbon = document.querySelector(`.workspace-ribbon.mod-${side}`);
        if (!ribbon)
          return;
        ribbon.querySelectorAll(".side-dock-ribbon-action, .clickable-icon, .workspace-ribbon-action").forEach((el) => {
          const element = el;
          const action = this.identifyAction(element);
          if (!action)
            return;
          if (!seen.has(action.actionId)) {
            seen.add(action.actionId);
            actions.push(action);
          }
        });
      });
      return actions;
    }
  };
  var main_default = SidebarOrganizerPlugin;
  return __toCommonJS(main_exports);
})();
module.exports = SidebarOrganizer;
